In [1]:
import pandas as pd
import numpy as np
import math
import csv

In [2]:
calib = pd.read_csv("get3alpha.csv", usecols=[0,3], names=["qcal", "qped"], encoding="utf8")
sigma = pd.read_csv("sigmas.csv", usecols=[0,1,2], names=["sigma_Gd", "sigma_Am", "sigma_Cm"], encoding="utf8")

In [3]:
dssd_ch = list(range(1,3+1,1))
b = np.array(dssd_ch)
energy_optical_resolution_Gd=[calib["qcal"]*(sigma["sigma_Gd"]-calib["qped"])*1000*2.35]
energy_optical_resolution_Am=[calib["qcal"]*(sigma["sigma_Am"]-calib["qped"])*1000*2.35]
energy_optical_resolution_Cm=[calib["qcal"]*(sigma["sigma_Cm"]-calib["qped"])*1000*2.35]

data = energy_optical_resolution_Gd
data += energy_optical_resolution_Am
data += energy_optical_resolution_Cm
a = np.array(data)
print(a.T)

[[60.094865   64.3273099  65.80336077]
 [42.8552249  55.13250853 52.84920541]
 [40.57765042 43.25853591 51.39845508]
 [37.55481301 43.39321513 45.06915218]
 [36.67668213 43.17144397 44.01121872]
 [40.55006757 45.38865511 47.2147034 ]
 [43.29294927 48.74892839 50.03541677]
 [38.42693788 42.35963934 44.53193161]
 [38.11782492 43.37541831 44.38980694]
 [37.70980782 42.38723274 50.70399744]
 [38.83411894 42.86416067 44.4910185 ]
 [37.79991809 41.91296785 43.46426019]
 [37.93365712 44.14335246 44.88810652]
 [40.10121897 52.60220586 52.10568169]
 [37.17189218 42.5906909  48.98310459]
 [43.32582052 53.41707535 49.14628067]
 [55.44507128 59.18188221 58.97526258]
 [43.29520862 54.09176956 52.92720267]
 [41.57931113 44.97488131 49.07563122]
 [45.39542236 51.50261626 50.66601435]
 [42.92143188 48.48517457 54.00766954]
 [48.70015933 50.97841757 50.03552328]
 [38.69237375 44.84294392 45.21448491]
 [40.53259029 46.89515948 48.04551199]
 [41.98429328 45.93826185 53.08949895]
 [45.36510119 57.16675859

In [5]:
with open('resolution.csv', 'w') as file:
    writer = csv.writer(file, lineterminator='\n')
    writer.writerows(a.T)